# Tokenization

Parsing text into tokens - words, punctuation or numbers

In [1]:
import re
import spacy
import pandas as pd

nlp = spacy.load('en_core_web_sm')

doc = nlp(open('./got2.txt').readline())
chapter = nlp(open('./got.txt').read())

print([token.text for token in doc])

['“', 'We', 'should', 'start', 'back', ',', '”', 'Gared', 'urged', 'as', 'the', 'woods', 'began', 'to', 'grow', 'dark', 'around', 'them', '.', '\n']

# Lemmatization

Reducing tokens to it's base forms.

In [2]:
df = pd.DataFrame([(token.text, token.lemma_) for token in doc], columns=['Token', 'Lemma'])

df.style

# Coarse-grained part-of-speech

Core parts of speech - noun, pronoun, determiner, adjective, verb, adverb, preposition, conjunction and interjection

In [3]:
pd.DataFrame([(token.text, token.pos_) for token in doc], columns=['Token','POS']).style

# Fine-grained part-of-speech

[part-of-speech with morphological features](https://github.com/explosion/spaCy/blob/master/spacy/glossary.py) such as tenses and types of pronouns.

In [4]:
pd.DataFrame([(token.text, token.tag_, spacy.explain(token.tag_)) for token in doc], columns=['Token', 'pos_', 'Explanation']).style

# Find quotes

In [9]:
for sentence in chapter.sents:
    quotes = re.findall(r"“(.*?)”", str(sentence))
    
    if len(quotes):
        print(quotes)

['We should start back,']
['The wildlings are dead.']
['Do the dead frighten you?']
['Dead is dead,']
['Are they dead?']
['What proof have we?']
['Will saw them,']
['If he says they are dead, that’s proof enough for me.']
['My wet nurse said the same thing, Will,']
['We have a long ride before us,']
['Bet he killed them all himself, he did,', 'twisted their little heads off, our mighty warrior.']